### PR TITLE
[Fixed] #3 Issue

### PR DESCRIPTION
**Pull request by Kristinita**
Fixed **#3** issue. See [**Packed vs. Unpacked**](https://packagecontrol.io/docs/customizing_packages).

1. `Preferences` → `Package Settings` → `DevSkim` → `Settings - Default` → default `DevSkim.sublime-settings` file is open.
2. Install [**Preferences Editor**](https://packagecontrol.io/packages/Preferences%20Editor) package → <kbd>Ctrl+Shift+P</kbd> → `Edit Preferences: Edit Settings` → `DevSkim` → I change settings → my settings will be apply to `User\DevSkim.sublime-settings` file.

Thanks.

### CODE REVIEW

**Comment by scovetta** [comment]
Thank you, @Kristinita! The automatic contributor license agreement widget wasn't in place (needed to merge your pull request)-- if you wouldn't mind, please go to [https://cla.microsoft.com](https://cla.microsoft.com) to fill this out.

**Comment by Kristinita** [comment]
@scovetta , [**I sign document**](http://nbviewer.jupyter.org/github/Kristinita/SashaMiscellaneous/blob/master/pdf/CLA%20-%20Microsoft.pdf#page=3). Should I do anything else?

Thanks.

**Comment by scovetta** [comment]
That's perfect, thank you!

**Comment by scovetta** [comment]
I'm going to close this PR because I fixed the issue a different way (by including the correct path in the menu config), covered in https://github.com/Microsoft/DevSkim-Sublime-Plugin/commit/a11084c9e3436ee8b64aca46734a7a1561168a5c. Appreciate the PR, though!!

**Pull request closed without merging**
